# Generated by Django 5.2.9 on 2026-01-05 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicebilling', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentRecord',
            new_name='PaymentTransaction',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicebilling.invoice'),
            preserve_default=False,
        ),
    ]
