# Generated by Django 5.2.9 on 2026-01-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicebilling', '0002_rename_paymentrecord_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicebilling.invoice'),
        ),
    ]
